#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

# Remove all existing rules before loading.
bspc rule -r "*"

# BSPWM configuration.
bspc config automatic_scheme              longest_side
bspc config split_ratio                   0.50
bspc config border_width                  3
bspc config window_gap                    0
bspc config top_padding                   35  # should be the same as polybar
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                true
bspc config borderless_monocle            true
bspc config gapless_monocle               false
bspc config focus_follows_pointer         true
bspc config pointer_follows_focus         false
bspc config pointer_follows_monitor       false
bspc config remove_disabled_monitors      true
bspc config remove_unplugged_monitors     true
bspc config merge_overlapping_monitors    true
bspc config center_pseudo_tiled           true
bspc config ignore_ewmh_focus             false

# mod1=Alt, mod4=super, mod5=AltGr
bspc config pointer_modifier mod1
bspc config pointer_action1  move
bspc config pointer_action2  resize_side
bspc config pointer_action3  resize_corner

# Borders and colors.
bspc config normal_border_color   "#3c3836"
bspc config active_border_color   "#3c3836"
bspc config focused_border_color  "#fb4934"
bspc config presel_feedback_color "#3c3836"

# Custom rules.
bspc rule -a Zathura state=tiled

# -----------------------------------------------
# Autostart.
#
nm-applet &
ibus-daemon -drx
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# -----------------------------------------------
# Scripts.
#
# Launch a compositor.
bash /usr/local/bin/compositor-init.sh &

# Run monitor setup script.
bash /usr/local/bin/bspwm-monitor-setup.sh &

# Run the refresh script. This contains programs and
# commands that usually require some kind of update
# or refresh from time to time, like when changing
# the monitor setup.
bash /usr/local/bin/bspwm-refresh.sh &
